# full list of application configuration's available at 
# https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/resources/application.yaml


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polaris-hapi-fhir-api
    username: polaris-hapi-fhir-api
    password: polaris-hapi-fhir-api
    driverClassName: org.postgresql.Driver
    max-active: 15
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
#      hibernate.hbm2ddl.auto: update
#      hibernate.jdbc.batch_size: 20
#      hibernate.cache.use_query_cache: false
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_structured_entries: false
#      hibernate.cache.use_minimal_puts: false

       # These settings will enable fulltext search with lucene
#      hibernate.search.enabled: true
#      hibernate.search.backend.type: lucene
#      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
#      hibernate.search.backend.directory.type: local-filesystem
#      hibernate.search.backend.directory.root: target/lucenefiles
#      hibernate.search.backend.lucene_version: lucene_current

  batch:
    job:
      enabled: false

hapi:
  fhir:
    ### enable to use the ApacheProxyAddressStrategy which uses X-Forwarded-* headers
    ###   to determine the FHIR server address
#   use_apache_address_strategy: false

    ### forces the use of the https:// protocol for the returned server address.
    ### alternatively, it may be set using the X-Forwarded-Proto header.
#   use_apache_address_strategy_https: false

    ### enable to set the Server URL
    server_address: http://localhost:8080/fhir

    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
    fhir_version: R4
#    defer_indexing_for_codesystems_of_size: 101

    #supported_resource_types:
    #  - Patient
    #  - Observation
    allow_cascading_deletes: true
    allow_contains_searches: true
#    allow_external_references: true
    allow_multiple_delete: true
#    allow_override_default_search_params: true
#    allow_placeholder_references: true
#    auto_create_placeholder_reference_targets: false
#    cql_enabled: true
#    default_encoding: JSON
#    default_pretty_print: true
#    default_page_size: 20
#    enable_repository_validating_interceptor: false
    enable_index_missing_fields: false
#    enforce_referential_integrity_on_delete: false
#    enforce_referential_integrity_on_write: false
    etag_support_enabled: true
    expunge_enabled: true
#    daoconfig_client_id_strategy: null
#    fhirpath_interceptor_enabled: false
    filter_search_enabled: true
    graphql_enabled: false
#    narrative_enabled: true
    #partitioning:
    #  allow_references_across_partitions: false
    #  partitioning_include_in_search_hashes: false
    #cors:
    #  allow_Credentials: true

      # Supports multiple, comma separated allowed origin entries
      # cors.allowed_origin=http://localhost:8080,https://localhost:8080,https://fhirtest.uhn.ca

    #  allowed_origin:
    #    - '*'

    server_client_id: SensyneHealth
    server_client_secret: UnbelievablyComplexPassword123qwerty

    tester:
      home:
        name: Local Tester
        server_address: http://localhost:8080/fhir
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
