version: 2.1
orbs:
  maven: circleci/maven@1.1
jobs:
  verify:
    docker:
    - image: circleci/openjdk:stretch
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-maven-dependencies-{{ checksum "pom.xml" }}
        - v1-maven-dependencies-
    - run:
        name: Verify and run HAPI FHIR integration tests
        command: mvn clean verify -f "pom.xml"
    - store_test_results:
        path: target/failsafe-reports
    - save_cache:
        paths:
        - ~/.m2
        key: v1-maven-dependencies-{{ checksum "pom.xml" }}
  deploy-dev:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - setup_remote_docker:
        version: version: 20.10.7
    - run:
        name: Add build information
        command: .circleci/record_build_info.sh
    - run:
          name: Build docker image
          command: docker build . -t polaris-hapi-fhir-api
    - run:
        name: Tag docker image
        command: |
        docker tag polaris-hapi-fhir-api ghcr.io/polaris-foundation/polaris-hapi-fhir-api:latest
        docker tag polaris-hapi-fhir-api ghcr.io/polaris-foundation/polaris-hapi-fhir-api:cb-${CIRCLE_BUILD_NUM}
        docker tag polaris-hapi-fhir-api ghcr.io/polaris-foundation/polaris-hapi-fhir-api:$(git log --pretty=format:'%h' -n 1)
    - run:
        name: Authenticate to GHCR
        command: echo $GHCR_TOKEN | docker login ghcr.io -u jonadaly --password-stdin
    - run:
        name: Push docker image
        command: |
        docker push ghcr.io/polaris-foundation/polaris-hapi-fhir-api:latest
        docker push ghcr.io/polaris-foundation/polaris-hapi-fhir-api:cb-${CIRCLE_BUILD_NUM}
        docker push ghcr.io/polaris-foundation/polaris-hapi-fhir-api:$(git log --pretty=format:'%h' -n 1)
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - deploy-dev:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main